checker:
  mysqlHost: 192.168.10.7
  mysqlUid: root
  mysqlPwd: Kidding!
  mysqlDatabase: factminr.scheduler
  mongoConn: mongodb://192.168.10.6:27017
  mongoDataBase: testbaidu
  mongoCollection: baidu